import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";
import { ASL_BUILT_IN_VOCABULARY } from "@/lib/model-adapters";

export const metadata: Metadata = { title: "Supported languages", description: "Honest language and vocabulary support for SignRelay." };

export default function LanguagesPage() {
  return <InfoPage eyebrow="Language support" title="Four languages. Four separate recognizers." intro="ASL, BSL, CSL and ISL are independent languages with different lexicons and grammar. SignRelay never shares a vocabulary by changing a label." sections={[
    { title: "American Sign Language · experimental", body: <><p>The installed research adapter includes the official WLASL2000 Pose-TGCN checkpoint. It is an isolated-sign research model, not full ASL translation, and the live MediaPipe-to-OpenPose adapter is still experimental.</p><p className="vocabulary-list"><strong>{ASL_BUILT_IN_VOCABULARY.length} built-in signs:</strong> {ASL_BUILT_IN_VOCABULARY.map((word) => word.gloss).join(" · ")}</p><p>Users can also type their own word or short phrase and record examples for a personal on-device recognizer. Those personal signs remain separate from the shared 2,000-word model.</p></> },
    { title: "British Sign Language · experimental", body: <><p>The installed official BSL-1K Pose2Sign checkpoint recognises 1,064 isolated BSL signs from 16 body-and-hand pose frames. The live camera path maps MediaPipe landmarks into the original model’s OpenPose input contract, so it is explicitly experimental rather than sentence translation.</p><p>You can separately teach any word or short phrase with private on-device examples. Those personal signs never replace or relabel the shared BSL model.</p><a href="https://github.com/gulvarol/bsl1k">Read the BSL-1K project</a></> },
    { title: "Indian Sign Language · experimental", body: <><p>The installed AI4Bharat INCLUDE transformer recognises 263 isolated ISL signs using 200 body-and-hand landmark frames. It runs locally with WebGPU/WASM; SignRelay applies a strict confidence and margin gate before outputting a label.</p><p>You can also teach private signs on this device. The shared 263-label model and private templates remain distinct.</p><a href="https://huggingface.co/datasets/ai4bharat/INCLUDE">Read the INCLUDE dataset card</a></> },
    { title: "Chinese Sign Language · 2,000+ concept library", body: <><p>Choose from more than 2,000 built-in sign-language concepts and record examples on this device; SignRelay matches them only inside the CSL workspace. The official SLR500 data remain research-access controlled, so the app does not claim a shared CSL model that it cannot substantiate.</p><a href="https://ustc-slr.github.io/datasets/2015_csl/">Read the SLR500 access requirements</a></> },
  ]} />;
}
