import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";
import { ASL_BUILT_IN_VOCABULARY, LANGUAGE_LIST, MODEL_ADAPTERS, PERSONAL_STARTER_VOCABULARY } from "@/lib/model-adapters";

export const metadata: Metadata = { title: "Model status", description: "Versions, inputs and limitations of SignRelay recognition models.", alternates: { canonical: "/models" } };

export default function ModelsPage() {
  const asl = MODEL_ADAPTERS.asl;
  const bsl = MODEL_ADAPTERS.bsl;
  const isl = MODEL_ADAPTERS.isl;
  const rsl = MODEL_ADAPTERS.rsl;
  return <InfoPage eyebrow="Model registry" title="No hidden claims." intro="A model is marked available only when the browser can load it and the UI names exactly what it supports." sections={[
    { title: "ASL starter · available, experimental", body: <dl className="model-spec"><div><dt>Version</dt><dd>{asl.version}</dd></div><div><dt>Model</dt><dd>{asl.modelFile}</dd></div><div><dt>Sequence</dt><dd>{asl.sequenceLength} frames</dd></div><div><dt>Threshold</dt><dd>{Math.round(asl.confidenceThreshold * 100)}%</dd></div><div><dt>Inputs</dt><dd>{asl.inputFormat}</dd></div><div><dt>Decoder</dt><dd>{asl.decoder}</dd></div></dl> },
    { title: "What is genuinely trained", body: <><p>The 2,000-word ASL model is the official WLASL2000 Pose-TGCN checkpoint trained on WLASL OpenPose sequences. BSL uses the official BSL-1K Pose2Sign body-and-hands checkpoint with 1,064 labels, and ISL uses AI4Bharat’s official INCLUDE landmark transformer with 263 labels. Each model runs locally from its own model file and label map.</p><p>All three are isolated-sign research models—not sentence translation—and their live MediaPipe adapters have not yet received signer-independent browser evaluation. They therefore remain experimental.</p><p>The landmark workspaces also offer signer-specific recognition from examples stored on that device. RSL uses the separate pretrained video mode described below.</p></> },
    { title: "Installed vocabulary contract", body: <p>{ASL_BUILT_IN_VOCABULARY.length} ASL, {bsl.automaticVocabularyCount.toLocaleString()} BSL, {isl.automaticVocabularyCount.toLocaleString()} ISL and {rsl.automaticVocabularyCount.toLocaleString()} RSL sign classes are installed without personal teaching as experimental isolated-sign models. RSL includes 967 word/phrase classes and 33 fingerspelling letters. The other {LANGUAGE_LIST.length - 4} workspaces offer {PERSONAL_STARTER_VOCABULARY.length.toLocaleString()} concept prompts and unlimited custom signs that activate only after the signer records examples. Prompts do not count toward pretrained coverage.</p> },
    { title: "RSL pretrained camera mode", body: <><p>Russian Sign Language uses the official Slovo MViTv2-small-32-2 ONNX checkpoint and its original label map. It reads 32 RGB video frames at about 15 fps, preserving the full frame through letterboxing. It does not require personal teaching. First load is 141 MB; single-thread WASM inference took about 19 seconds in the development environment, so RSL uses explicit single-sign capture with cancellation rather than the live landmark loop.</p><p>Blank output, low scores and static clips are rejected. A high model score is not proof of a correct translation. Independent live-camera and native-signer accuracy remain unmeasured. Results are not automatically spoken or inserted into a transcript.</p><p><a href="/models/rsl1000-slovo/ATTRIBUTION.md">Attribution, changes and evaluation limits</a> · <a href="/models/rsl1000-slovo/LICENSE.pdf">Slovo custom attribution/share-alike licence</a>. This is separate from SignRelay’s application-code licence.</p></> },
    { title: "Research datasets", body: <ul><li><a href="https://dxli94.github.io/WLASL/">WLASL</a>: 2,000 word-level ASL signs, academic/computational use restrictions.</li><li><a href="https://github.com/gulvarol/bsl1k">BSL-1K</a>: the source for SignRelay’s 1,064-label BSL Pose2Sign checkpoint.</li><li><a href="https://huggingface.co/datasets/ai4bharat/INCLUDE">INCLUDE</a>: CC-BY-4.0 ISL data and the official 263-label landmark checkpoint used by SignRelay.</li><li><a href="https://zenodo.org/records/13691887">SWL-LSE</a>: open 300-sign Spanish Sign Language health-domain landmark release used for the LSE build.</li><li><a href="https://github.com/UQ-CVLab/MM-WLAuslan-Dataset">MM-WLAuslan</a>: 3,215-gloss Auslan data under CC BY-NC-SA 4.0; a browser model is not yet installed.</li><li><a href="https://ustc-slr.github.io/datasets/2015_csl/">SLR500</a>: 500 isolated CSL signs, but access requires a full-time-staff-signed research agreement.</li></ul> },
  ]} />;
}
