import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";
import { ASL_BUILT_IN_VOCABULARY, LANGUAGE_LIST, MODEL_ADAPTERS, PERSONAL_STARTER_VOCABULARY } from "@/lib/model-adapters";

export const metadata: Metadata = { title: "Model status", description: "Versions, inputs and limitations of SignRelay recognition models.", alternates: { canonical: "/models" } };

export default function ModelsPage() {
  const asl = MODEL_ADAPTERS.asl;
  const bsl = MODEL_ADAPTERS.bsl;
  const isl = MODEL_ADAPTERS.isl;
  const rsl = MODEL_ADAPTERS.rsl;
  const psl = MODEL_ADAPTERS.psl;
  const automatic = LANGUAGE_LIST.filter(language => language.status === "experimental");
  return <InfoPage eyebrow="Model registry" title="No hidden claims." intro="A model is marked available only when the browser can load it and the UI names exactly what it supports." sections={[
    { title: "ASL starter · available, experimental", body: <dl className="model-spec"><div><dt>Version</dt><dd>{asl.version}</dd></div><div><dt>Model</dt><dd>{asl.modelFile}</dd></div><div><dt>Sequence</dt><dd>{asl.sequenceLength} frames</dd></div><div><dt>Threshold</dt><dd>{Math.round(asl.confidenceThreshold * 100)}%</dd></div><div><dt>Inputs</dt><dd>{asl.inputFormat}</dd></div><div><dt>Decoder</dt><dd>{asl.decoder}</dd></div></dl> },
    { title: "What is genuinely trained", body: <><p>The 2,000-word ASL model is the official WLASL2000 Pose-TGCN checkpoint trained on WLASL OpenPose sequences. BSL uses the official BSL-1K Pose2Sign body-and-hands checkpoint with 1,064 labels, and ISL uses AI4Bharat’s official INCLUDE landmark transformer with 263 labels. Each model runs locally from its own model file and label map.</p><p>All three are isolated-sign research models—not sentence translation—and their live MediaPipe adapters have not yet received signer-independent browser evaluation. They therefore remain experimental.</p><p>The landmark workspaces also offer signer-specific recognition from examples stored on that device. RSL uses the separate pretrained video mode described below.</p></> },
    { title: "Installed vocabulary contract", body: <p>{ASL_BUILT_IN_VOCABULARY.length} ASL, {bsl.automaticVocabularyCount.toLocaleString()} BSL, {isl.automaticVocabularyCount.toLocaleString()} ISL, {rsl.automaticVocabularyCount.toLocaleString()} RSL, 300 Spanish, 401 Bangla and {psl.automaticVocabularyCount.toLocaleString()} PSL signs are installed without personal teaching. RSL includes 967 word/phrase classes and 33 fingerspelling letters. Bangla has 398 distinct English glosses for its 401 classes. PSL’s {psl.automaticVocabularyCount.toLocaleString()} are official reference signs matched one-shot, not a trained classifier’s output classes; see below. The other {LANGUAGE_LIST.length - automatic.length} workspaces offer {PERSONAL_STARTER_VOCABULARY.length.toLocaleString()} concept prompts and unlimited custom signs that activate only after the signer records examples. Prompts do not count toward pretrained coverage.</p> },
    { title: "RSL pretrained camera mode", body: <><p>Russian Sign Language uses the official Slovo MViTv2-small-32-2 ONNX checkpoint and its original label map. It reads 32 RGB video frames at about 15 fps, preserving the full frame through letterboxing. It does not require personal teaching. First load is 141 MB; single-thread WASM inference took about 19 seconds in the development environment, so RSL uses explicit single-sign capture with cancellation rather than the live landmark loop.</p><p>Blank output, low scores and static clips are rejected. A high model score is not proof of a correct translation. Independent live-camera and native-signer accuracy remain unmeasured. Results are not automatically spoken or inserted into a transcript.</p><p><a href="/models/rsl1000-slovo/ATTRIBUTION.md">Attribution, changes and evaluation limits</a> · <a href="/models/rsl1000-slovo/LICENSE.pdf">Slovo custom attribution/share-alike licence</a>. This is separate from SignRelay’s application-code licence.</p></> },
    { title: "Bangla pretrained camera mode", body: <><p>Bangla Sign Language now has a 401-class VideoMAE model with 398 distinct English glosses. It captures one sign at a time, runs locally in a separate worker, and lets you cancel. The 97 MB model uses compressed weights with float32 arithmetic; the browser preprocessing has been compared with the original PyTorch input on six pinned publisher clips.</p><p>This is a slow research preview. Static scenes and uncertain scores are rejected, but incorrect suggestions are still possible. Publisher-selected clips do not establish independent signer or live-camera accuracy. Outputs are not automatically spoken or inserted into a transcript.</p><p><a href="/models/bdsl401-videomae/ATTRIBUTION.md">Model and dataset attribution, terms, and limitations</a></p></> },
    { title: "Spanish pretrained landmark model", body: <><p>Spanish Sign Language has a 300-class SWL-LSE health-domain model trained for SignRelay. The 3.5 MB checkpoint and original Spanish labels run locally. It reached 706/1,052 correct on the released validation split and 363/600 on the test split (60.5%). These are dataset results; independent signer and live-camera accuracy remain unmeasured.</p><p>The browser input transform is checked against the training reader, including longer clips and missing landmarks. Motion, confidence and consensus gates reduce uncertain output; they cannot guarantee a correct translation. Personal examples retain priority.</p><p><a href="/models/lse300-swl/ATTRIBUTION.md">Spanish model attribution and evaluation limits</a></p></> },
    { title: "PSL: one-shot reference matching, not a trained classifier", body: <><p>Pakistan Sign Language is different in kind from the other six installed languages. It has no trained model. Each of its {psl.automaticVocabularyCount.toLocaleString()} signs comes from exactly one official performance recorded at Hamza Foundation Academy for the Deaf, and recognition works by dynamic-time-warping distance to that single reference &mdash; the same one-shot matching already used for a signer’s own personal templates, just against a built-in library instead of self-recorded examples.</p><p>No accuracy figure exists for PSL: not a held-out split, not a publisher-clip test, nothing. Treat it as roughly as reliable as matching a single well-performed personal recording &mdash; sensitive to signing speed, style and camera framing. It runs continuously like ASL/BSL/ISL/LSE, not as RSL/Bangla’s slow single-capture mode. Personal examples retain priority.</p><p><a href="/models/psl776-hfad/ATTRIBUTION.md">PSL template attribution and evaluation limits</a></p></> },
    { title: "Progress toward 15 languages", body: <><p>{automatic.length} languages currently have installed experimental recognition. {automatic.filter(language => language.automaticVocabularyCount >= 400).length} have at least 400 automatic classes. Not all of those are trained classifiers, and classes are not always distinct words: Bangla has 398 English glosses, RSL includes letters, and PSL’s classes are one-shot reference matches rather than a classifier’s output. The 15-language, 400-word target remains unfinished.</p><p>Korean remains a research candidate with unresolved reuse terms and tracker integration. Indian recognition currently covers 263 classes. The Spanish training dataset has 300 classes; successful training alone will not meet a 400-word target.</p></> },
    { title: "Research datasets", body: <ul><li><a href="https://dxli94.github.io/WLASL/">WLASL</a>: 2,000 word-level ASL signs, academic/computational use restrictions.</li><li><a href="https://github.com/gulvarol/bsl1k">BSL-1K</a>: the source for SignRelay’s 1,064-label BSL Pose2Sign checkpoint.</li><li><a href="https://huggingface.co/datasets/ai4bharat/INCLUDE">INCLUDE</a>: CC-BY-4.0 ISL data and the official 263-label landmark checkpoint used by SignRelay.</li><li><a href="https://zenodo.org/records/13691887">SWL-LSE</a>: open 300-sign Spanish Sign Language health-domain landmark release used for the LSE build.</li><li><a href="https://github.com/sign-language-translator/sign-language-datasets">HFAD PSL dictionary</a>: CC BY 4.0, 775 Pakistan Sign Language signs used as one-shot reference templates, not training data.</li><li><a href="https://github.com/UQ-CVLab/MM-WLAuslan-Dataset">MM-WLAuslan</a>: 3,215-gloss Auslan data under CC BY-NC-SA 4.0; a browser model is not yet installed.</li><li><a href="https://ustc-slr.github.io/datasets/2015_csl/">SLR500</a>: 500 isolated CSL signs, but access requires a full-time-staff-signed research agreement.</li></ul> },
  ]} />;
}
